// Code generated by "stringer -type=Profile"; DO NOT EDIT.

package copp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unspecified-0]
	_ = x[Unknown-1]
	_ = x[Strict-2]
	_ = x[Moderate-3]
	_ = x[Dense-4]
	_ = x[Lenient-5]
}

const _Profile_name = "UnspecifiedUnknownStrictModerateDenseLenient"

var _Profile_index = [...]uint8{0, 11, 18, 24, 32, 37, 44}

func (i Profile) String() string {
	if i < 0 || i >= Profile(len(_Profile_index)-1) {
		return "Profile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Profile_name[_Profile_index[i]:_Profile_index[i+1]]
}
