apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Interface
metadata:
  labels:
    networking.metal.ironcore.dev/role: fabric
  name: spine1-eth1-1
spec:
  deviceRef:
    name: spine1
  name: eth1/1
  description: Spine1 to Leaf1
  adminState: Up
  type: Physical
  mtu: 9216
  ipv4:
    unnumbered:
      interfaceRef:
        name: spine1-lo0
