// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

/*
Package genyang is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/I753012/.go/pkg/mod/github.com/openconfig/ygot@v0.32.0/genutil/names.go
using the following YANG input files:
  - Cisco-NX-OS-device.yang

Imported modules were sourced from:
*/
package genyang

import (
	"fmt"
)

// Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/acl-items/ipv4-items/statClear-items/timeStamp within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union() {
}

// Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union() {
}

// To_Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems) To_Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union(i interface{}) (Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_AclItems_Ipv4Items_StatClearItems_TimeStamp_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}

// Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/acl-items/ipv6-items/statClear-items/timeStamp within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union() {
}

// Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union() {
}

// To_Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems) To_Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union(i interface{}) (Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_AclItems_Ipv6Items_StatClearItems_TimeStamp_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}

// Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/acl-items/mac-items/statClear-items/timeStamp within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union() {
}

// Documentation_for_Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union() {
}

// To_Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems) To_Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union(i interface{}) (Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_AclItems_MacItems_StatClearItems_TimeStamp_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}

// Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/acllog-items/inst-items/log-items/interval within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union() {
}

// Documentation_for_Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union() {
}

// To_Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems) To_Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union(i interface{}) (Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_AcllogItems_InstItems_LogItems_Interval_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}

// Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/systemTable-items/purgeDBRequest within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union() {
}

// Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union() {
}

// To_Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_SystemTableItems) To_Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union(i interface{}) (Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_SystemTableItems_PurgeDBRequest_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}

// Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/systemTable-items/stTime within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union() {}

// Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union() {}

// To_Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_SystemTableItems) To_Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union(i interface{}) (Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_SystemTableItems_StTime_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}

// Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/track-items/object-items/Object-list/delayDown within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union() {
}

// Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union() {
}

// To_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList) To_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union(i interface{}) (Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayDown_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}

// Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/track-items/object-items/Object-list/delayUp within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union() {
}

// Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union() {
}

// To_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList) To_Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union(i interface{}) (Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_TrackItems_ObjectItems_ObjectList_DelayUp_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}

// Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union is an interface that is implemented by valid types for the union
// for the leaf /Cisco-NX-OS-device/System/userext-items/user-items/User-list/expiration within the YANG schema.
// Union type can be one of [UnionString, UnionUint64].
type Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union interface {
	// Union type can be one of [UnionString, UnionUint64]
	Documentation_for_Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union()
}

// Documentation_for_Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union ensures that UnionString
// implements the Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union interface.
func (UnionString) Documentation_for_Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union() {
}

// Documentation_for_Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union ensures that UnionUint64
// implements the Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union interface.
func (UnionUint64) Documentation_for_Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union() {
}

// To_Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList) To_Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union(i interface{}) (Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union, error) {
	if v, ok := i.(Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint64:
		return UnionUint64(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Cisco_NX_OSDevice_System_UserextItems_UserItems_UserList_Expiration_Union, unknown union type, got: %T, want any of [string, uint64]", i, i)
}
