apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - spanning-tree-network.yaml
  - leaf1-eth1-31.yaml
  - leaf1-eth1-32.yaml
  - leaf1-po1.yaml
  - leaf2-eth1-31.yaml
  - leaf2-eth1-32.yaml
  - leaf2-po1.yaml
