apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Interface
metadata:
  labels:
    networking.metal.ironcore.dev/role: vpc-peer-link
  name: leaf1-eth1-32
spec:
  deviceRef:
    name: leaf1
  providerConfigRef:
    apiVersion: nx.cisco.networking.metal.ironcore.dev/v1alpha1
    kind: InterfaceConfig
    name: spanning-tree-network
  name: eth1/32
  description: vPC Peer-Link
  adminState: Up
  type: Physical
  switchport:
    mode: Trunk
    nativeVlan: 1
