// Code generated by "stringer -type=Action"; DO NOT EDIT.

package acl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Permit-1]
	_ = x[Deny-2]
}

const _Action_name = "PermitDeny"

var _Action_index = [...]uint8{0, 6, 10}

func (i Action) String() string {
	i -= 1
	if i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
