// Code generated by "stringer -type=TransportMode"; DO NOT EDIT.

package smartlicensing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransportOff-0]
	_ = x[TransportSmart-1]
	_ = x[TransportCSLU-2]
	_ = x[TransportCallhome-3]
}

const _TransportMode_name = "TransportOffTransportSmartTransportCSLUTransportCallhome"

var _TransportMode_index = [...]uint8{0, 12, 26, 39, 56}

func (i TransportMode) String() string {
	if i >= TransportMode(len(_TransportMode_index)-1) {
		return "TransportMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransportMode_name[_TransportMode_index[i]:_TransportMode_index[i+1]]
}
