// Code generated by "stringer -type=PasswordType"; DO NOT EDIT.

package localusr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PasswdType5-1]
	_ = x[PasswdTypePbkdf2-2]
	_ = x[PasswdTypeScrypt-3]
}

const _PasswordType_name = "PasswdType5PasswdTypePbkdf2PasswdTypeScrypt"

var _PasswordType_index = [...]uint8{0, 11, 27, 43}

func (i PasswordType) String() string {
	i -= 1
	if i < 0 || i >= PasswordType(len(_PasswordType_index)-1) {
		return "PasswordType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PasswordType_name[_PasswordType_index[i]:_PasswordType_index[i+1]]
}
