// Code generated by "stringer -type=PrivType"; DO NOT EDIT.

package localusr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoDataPriv-0]
	_ = x[ReadPriv-1]
	_ = x[WritePriv-2]
}

const _PrivType_name = "NoDataPrivReadPrivWritePriv"

var _PrivType_index = [...]uint8{0, 10, 18, 27}

func (i PrivType) String() string {
	if i < 0 || i >= PrivType(len(_PrivType_index)-1) {
		return "PrivType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrivType_name[_PrivType_index[i]:_PrivType_index[i+1]]
}
