// Code generated by "stringer -type=ShellType"; DO NOT EDIT.

package localusr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VSH-1]
	_ = x[Bash-2]
}

const _ShellType_name = "VSHBash"

var _ShellType_index = [...]uint8{0, 3, 7}

func (i ShellType) String() string {
	i -= 1
	if i < 0 || i >= ShellType(len(_ShellType_index)-1) {
		return "ShellType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ShellType_name[_ShellType_index[i]:_ShellType_index[i+1]]
}
