// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package gnmiext

import (
	"context"
	"sync"

	gpb "github.com/openconfig/gnmi/proto/gnmi"
	"github.com/openconfig/ygot/ygot"
	"google.golang.org/grpc"
)

// Ensure, that GNMIClientMock does implement GNMIClient.
// If this is not the case, regenerate this file with moq.
var _ GNMIClient = &GNMIClientMock{}

// GNMIClientMock is a mock implementation of GNMIClient.
//
//	func TestSomethingThatUsesGNMIClient(t *testing.T) {
//
//		// make and configure a mocked GNMIClient
//		mockedGNMIClient := &GNMIClientMock{
//			CapabilitiesFunc: func(ctx context.Context, in *gpb.CapabilityRequest, opts ...grpc.CallOption) (*gpb.CapabilityResponse, error) {
//				panic("mock out the Capabilities method")
//			},
//			GetFunc: func(ctx context.Context, in *gpb.GetRequest, opts ...grpc.CallOption) (*gpb.GetResponse, error) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, in *gpb.SetRequest, opts ...grpc.CallOption) (*gpb.SetResponse, error) {
//				panic("mock out the Set method")
//			},
//			SubscribeFunc: func(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[gpb.SubscribeRequest, gpb.SubscribeResponse], error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedGNMIClient in code that requires GNMIClient
//		// and then make assertions.
//
//	}
type GNMIClientMock struct {
	// CapabilitiesFunc mocks the Capabilities method.
	CapabilitiesFunc func(ctx context.Context, in *gpb.CapabilityRequest, opts ...grpc.CallOption) (*gpb.CapabilityResponse, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, in *gpb.GetRequest, opts ...grpc.CallOption) (*gpb.GetResponse, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, in *gpb.SetRequest, opts ...grpc.CallOption) (*gpb.SetResponse, error)

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[gpb.SubscribeRequest, gpb.SubscribeResponse], error)

	// calls tracks calls to the methods.
	calls struct {
		// Capabilities holds details about calls to the Capabilities method.
		Capabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *gpb.CapabilityRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *gpb.GetRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *gpb.SetRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockCapabilities sync.RWMutex
	lockGet          sync.RWMutex
	lockSet          sync.RWMutex
	lockSubscribe    sync.RWMutex
}

// Capabilities calls CapabilitiesFunc.
func (mock *GNMIClientMock) Capabilities(ctx context.Context, in *gpb.CapabilityRequest, opts ...grpc.CallOption) (*gpb.CapabilityResponse, error) {
	if mock.CapabilitiesFunc == nil {
		panic("GNMIClientMock.CapabilitiesFunc: method is nil but GNMIClient.Capabilities was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *gpb.CapabilityRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockCapabilities.Lock()
	mock.calls.Capabilities = append(mock.calls.Capabilities, callInfo)
	mock.lockCapabilities.Unlock()
	return mock.CapabilitiesFunc(ctx, in, opts...)
}

// CapabilitiesCalls gets all the calls that were made to Capabilities.
// Check the length with:
//
//	len(mockedGNMIClient.CapabilitiesCalls())
func (mock *GNMIClientMock) CapabilitiesCalls() []struct {
	Ctx  context.Context
	In   *gpb.CapabilityRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *gpb.CapabilityRequest
		Opts []grpc.CallOption
	}
	mock.lockCapabilities.RLock()
	calls = mock.calls.Capabilities
	mock.lockCapabilities.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *GNMIClientMock) Get(ctx context.Context, in *gpb.GetRequest, opts ...grpc.CallOption) (*gpb.GetResponse, error) {
	if mock.GetFunc == nil {
		panic("GNMIClientMock.GetFunc: method is nil but GNMIClient.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *gpb.GetRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, in, opts...)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedGNMIClient.GetCalls())
func (mock *GNMIClientMock) GetCalls() []struct {
	Ctx  context.Context
	In   *gpb.GetRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *gpb.GetRequest
		Opts []grpc.CallOption
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *GNMIClientMock) Set(ctx context.Context, in *gpb.SetRequest, opts ...grpc.CallOption) (*gpb.SetResponse, error) {
	if mock.SetFunc == nil {
		panic("GNMIClientMock.SetFunc: method is nil but GNMIClient.Set was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *gpb.SetRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, in, opts...)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedGNMIClient.SetCalls())
func (mock *GNMIClientMock) SetCalls() []struct {
	Ctx  context.Context
	In   *gpb.SetRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *gpb.SetRequest
		Opts []grpc.CallOption
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *GNMIClientMock) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[gpb.SubscribeRequest, gpb.SubscribeResponse], error) {
	if mock.SubscribeFunc == nil {
		panic("GNMIClientMock.SubscribeFunc: method is nil but GNMIClient.Subscribe was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, opts...)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedGNMIClient.SubscribeCalls())
func (mock *GNMIClientMock) SubscribeCalls() []struct {
	Ctx  context.Context
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		Opts []grpc.CallOption
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			GetFunc: func(ctx context.Context, xpath string, dest ygot.GoStruct) error {
//				panic("mock out the Get method")
//			},
//			ResetFunc: func(ctx context.Context, config DeviceConf) error {
//				panic("mock out the Reset method")
//			},
//			SetFunc: func(ctx context.Context, notification *gpb.Notification) error {
//				panic("mock out the Set method")
//			},
//			UpdateFunc: func(ctx context.Context, config DeviceConf) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, xpath string, dest ygot.GoStruct) error

	// ResetFunc mocks the Reset method.
	ResetFunc func(ctx context.Context, config DeviceConf) error

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, notification *gpb.Notification) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, config DeviceConf) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Xpath is the xpath argument value.
			Xpath string
			// Dest is the dest argument value.
			Dest ygot.GoStruct
		}
		// Reset holds details about calls to the Reset method.
		Reset []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Config is the config argument value.
			Config DeviceConf
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Notification is the notification argument value.
			Notification *gpb.Notification
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Config is the config argument value.
			Config DeviceConf
		}
	}
	lockGet    sync.RWMutex
	lockReset  sync.RWMutex
	lockSet    sync.RWMutex
	lockUpdate sync.RWMutex
}

// Get calls GetFunc.
func (mock *ClientMock) Get(ctx context.Context, xpath string, dest ygot.GoStruct) error {
	if mock.GetFunc == nil {
		panic("ClientMock.GetFunc: method is nil but Client.Get was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Xpath string
		Dest  ygot.GoStruct
	}{
		Ctx:   ctx,
		Xpath: xpath,
		Dest:  dest,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, xpath, dest)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedClient.GetCalls())
func (mock *ClientMock) GetCalls() []struct {
	Ctx   context.Context
	Xpath string
	Dest  ygot.GoStruct
} {
	var calls []struct {
		Ctx   context.Context
		Xpath string
		Dest  ygot.GoStruct
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Reset calls ResetFunc.
func (mock *ClientMock) Reset(ctx context.Context, config DeviceConf) error {
	if mock.ResetFunc == nil {
		panic("ClientMock.ResetFunc: method is nil but Client.Reset was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Config DeviceConf
	}{
		Ctx:    ctx,
		Config: config,
	}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	return mock.ResetFunc(ctx, config)
}

// ResetCalls gets all the calls that were made to Reset.
// Check the length with:
//
//	len(mockedClient.ResetCalls())
func (mock *ClientMock) ResetCalls() []struct {
	Ctx    context.Context
	Config DeviceConf
} {
	var calls []struct {
		Ctx    context.Context
		Config DeviceConf
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *ClientMock) Set(ctx context.Context, notification *gpb.Notification) error {
	if mock.SetFunc == nil {
		panic("ClientMock.SetFunc: method is nil but Client.Set was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Notification *gpb.Notification
	}{
		Ctx:          ctx,
		Notification: notification,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, notification)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedClient.SetCalls())
func (mock *ClientMock) SetCalls() []struct {
	Ctx          context.Context
	Notification *gpb.Notification
} {
	var calls []struct {
		Ctx          context.Context
		Notification *gpb.Notification
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ClientMock) Update(ctx context.Context, config DeviceConf) error {
	if mock.UpdateFunc == nil {
		panic("ClientMock.UpdateFunc: method is nil but Client.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Config DeviceConf
	}{
		Ctx:    ctx,
		Config: config,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, config)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedClient.UpdateCalls())
func (mock *ClientMock) UpdateCalls() []struct {
	Ctx    context.Context
	Config DeviceConf
} {
	var calls []struct {
		Ctx    context.Context
		Config DeviceConf
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
