//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/ironcore-dev/network-operator/api/core/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRecovery) DeepCopyInto(out *AutoRecovery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRecovery.
func (in *AutoRecovery) DeepCopy() *AutoRecovery {
	if in == nil {
		return nil
	}
	out := new(AutoRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeerReference) DeepCopyInto(out *BGPPeerReference) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeerReference.
func (in *BGPPeerReference) DeepCopy() *BGPPeerReference {
	if in == nil {
		return nil
	}
	out := new(BGPPeerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BorderGateway) DeepCopyInto(out *BorderGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BorderGateway.
func (in *BorderGateway) DeepCopy() *BorderGateway {
	if in == nil {
		return nil
	}
	out := new(BorderGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BorderGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BorderGatewayList) DeepCopyInto(out *BorderGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BorderGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BorderGatewayList.
func (in *BorderGatewayList) DeepCopy() *BorderGatewayList {
	if in == nil {
		return nil
	}
	out := new(BorderGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BorderGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BorderGatewaySpec) DeepCopyInto(out *BorderGatewaySpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	out.SourceInterfaceRef = in.SourceInterfaceRef
	out.DelayRestoreTime = in.DelayRestoreTime
	if in.InterconnectInterfaceRefs != nil {
		in, out := &in.InterconnectInterfaceRefs, &out.InterconnectInterfaceRefs
		*out = make([]InterconnectInterfaceReference, len(*in))
		copy(*out, *in)
	}
	if in.BGPPeerRefs != nil {
		in, out := &in.BGPPeerRefs, &out.BGPPeerRefs
		*out = make([]BGPPeerReference, len(*in))
		copy(*out, *in)
	}
	if in.StormControl != nil {
		in, out := &in.StormControl, &out.StormControl
		*out = make([]StormControl, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BorderGatewaySpec.
func (in *BorderGatewaySpec) DeepCopy() *BorderGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(BorderGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BorderGatewayStatus) DeepCopyInto(out *BorderGatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BorderGatewayStatus.
func (in *BorderGatewayStatus) DeepCopy() *BorderGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(BorderGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BufferBoost) DeepCopyInto(out *BufferBoost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BufferBoost.
func (in *BufferBoost) DeepCopy() *BufferBoost {
	if in == nil {
		return nil
	}
	out := new(BufferBoost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Console) DeepCopyInto(out *Console) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Console.
func (in *Console) DeepCopy() *Console {
	if in == nil {
		return nil
	}
	out := new(Console)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Enabled) DeepCopyInto(out *Enabled) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Enabled.
func (in *Enabled) DeepCopy() *Enabled {
	if in == nil {
		return nil
	}
	out := new(Enabled)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterconnectInterfaceReference) DeepCopyInto(out *InterconnectInterfaceReference) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterconnectInterfaceReference.
func (in *InterconnectInterfaceReference) DeepCopy() *InterconnectInterfaceReference {
	if in == nil {
		return nil
	}
	out := new(InterconnectInterfaceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceConfig) DeepCopyInto(out *InterfaceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceConfig.
func (in *InterfaceConfig) DeepCopy() *InterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(InterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InterfaceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceConfigList) DeepCopyInto(out *InterfaceConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceConfigList.
func (in *InterfaceConfigList) DeepCopy() *InterfaceConfigList {
	if in == nil {
		return nil
	}
	out := new(InterfaceConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InterfaceConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceConfigSpec) DeepCopyInto(out *InterfaceConfigSpec) {
	*out = *in
	if in.SpanningTree != nil {
		in, out := &in.SpanningTree, &out.SpanningTree
		*out = new(SpanningTree)
		(*in).DeepCopyInto(*out)
	}
	if in.BufferBoost != nil {
		in, out := &in.BufferBoost, &out.BufferBoost
		*out = new(BufferBoost)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceConfigSpec.
func (in *InterfaceConfigSpec) DeepCopy() *InterfaceConfigSpec {
	if in == nil {
		return nil
	}
	out := new(InterfaceConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeepAlive) DeepCopyInto(out *KeepAlive) {
	*out = *in
	if in.VRFRef != nil {
		in, out := &in.VRFRef, &out.VRFRef
		*out = new(corev1alpha1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeepAlive.
func (in *KeepAlive) DeepCopy() *KeepAlive {
	if in == nil {
		return nil
	}
	out := new(KeepAlive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementAccessConfig) DeepCopyInto(out *ManagementAccessConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementAccessConfig.
func (in *ManagementAccessConfig) DeepCopy() *ManagementAccessConfig {
	if in == nil {
		return nil
	}
	out := new(ManagementAccessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementAccessConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementAccessConfigList) DeepCopyInto(out *ManagementAccessConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementAccessConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementAccessConfigList.
func (in *ManagementAccessConfigList) DeepCopy() *ManagementAccessConfigList {
	if in == nil {
		return nil
	}
	out := new(ManagementAccessConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementAccessConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementAccessConfigSpec) DeepCopyInto(out *ManagementAccessConfigSpec) {
	*out = *in
	out.Console = in.Console
	out.SSH = in.SSH
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementAccessConfigSpec.
func (in *ManagementAccessConfigSpec) DeepCopy() *ManagementAccessConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementAccessConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVirtualizationEdgeConfig) DeepCopyInto(out *NetworkVirtualizationEdgeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVirtualizationEdgeConfig.
func (in *NetworkVirtualizationEdgeConfig) DeepCopy() *NetworkVirtualizationEdgeConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkVirtualizationEdgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkVirtualizationEdgeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVirtualizationEdgeConfigList) DeepCopyInto(out *NetworkVirtualizationEdgeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkVirtualizationEdgeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVirtualizationEdgeConfigList.
func (in *NetworkVirtualizationEdgeConfigList) DeepCopy() *NetworkVirtualizationEdgeConfigList {
	if in == nil {
		return nil
	}
	out := new(NetworkVirtualizationEdgeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkVirtualizationEdgeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVirtualizationEdgeConfigSpec) DeepCopyInto(out *NetworkVirtualizationEdgeConfigSpec) {
	*out = *in
	if in.InfraVLANs != nil {
		in, out := &in.InfraVLANs, &out.InfraVLANs
		*out = make([]VLANListItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVirtualizationEdgeConfigSpec.
func (in *NetworkVirtualizationEdgeConfigSpec) DeepCopy() *NetworkVirtualizationEdgeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkVirtualizationEdgeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Peer) DeepCopyInto(out *Peer) {
	*out = *in
	out.InterfaceRef = in.InterfaceRef
	in.KeepAlive.DeepCopyInto(&out.KeepAlive)
	if in.AutoRecovery != nil {
		in, out := &in.AutoRecovery, &out.AutoRecovery
		*out = new(AutoRecovery)
		**out = **in
	}
	out.Switch = in.Switch
	out.Gateway = in.Gateway
	out.L3Router = in.L3Router
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Peer.
func (in *Peer) DeepCopy() *Peer {
	if in == nil {
		return nil
	}
	out := new(Peer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSH) DeepCopyInto(out *SSH) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSH.
func (in *SSH) DeepCopy() *SSH {
	if in == nil {
		return nil
	}
	out := new(SSH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanningTree) DeepCopyInto(out *SpanningTree) {
	*out = *in
	if in.BPDUGuard != nil {
		in, out := &in.BPDUGuard, &out.BPDUGuard
		*out = new(bool)
		**out = **in
	}
	if in.BPDUFilter != nil {
		in, out := &in.BPDUFilter, &out.BPDUFilter
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanningTree.
func (in *SpanningTree) DeepCopy() *SpanningTree {
	if in == nil {
		return nil
	}
	out := new(SpanningTree)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StormControl) DeepCopyInto(out *StormControl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StormControl.
func (in *StormControl) DeepCopy() *StormControl {
	if in == nil {
		return nil
	}
	out := new(StormControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *System) DeepCopyInto(out *System) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new System.
func (in *System) DeepCopy() *System {
	if in == nil {
		return nil
	}
	out := new(System)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *System) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemList) DeepCopyInto(out *SystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]System, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemList.
func (in *SystemList) DeepCopy() *SystemList {
	if in == nil {
		return nil
	}
	out := new(SystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemSpec) DeepCopyInto(out *SystemSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemSpec.
func (in *SystemSpec) DeepCopy() *SystemSpec {
	if in == nil {
		return nil
	}
	out := new(SystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemStatus) DeepCopyInto(out *SystemStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemStatus.
func (in *SystemStatus) DeepCopy() *SystemStatus {
	if in == nil {
		return nil
	}
	out := new(SystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANListItem) DeepCopyInto(out *VLANListItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANListItem.
func (in *VLANListItem) DeepCopy() *VLANListItem {
	if in == nil {
		return nil
	}
	out := new(VLANListItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDomain) DeepCopyInto(out *VPCDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDomain.
func (in *VPCDomain) DeepCopy() *VPCDomain {
	if in == nil {
		return nil
	}
	out := new(VPCDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDomainList) DeepCopyInto(out *VPCDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDomainList.
func (in *VPCDomainList) DeepCopy() *VPCDomainList {
	if in == nil {
		return nil
	}
	out := new(VPCDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDomainSpec) DeepCopyInto(out *VPCDomainSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	out.FastConvergence = in.FastConvergence
	in.Peer.DeepCopyInto(&out.Peer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDomainSpec.
func (in *VPCDomainSpec) DeepCopy() *VPCDomainSpec {
	if in == nil {
		return nil
	}
	out := new(VPCDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCDomainStatus) DeepCopyInto(out *VPCDomainStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeepAliveStatusMsg != nil {
		in, out := &in.KeepAliveStatusMsg, &out.KeepAliveStatusMsg
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PeerStatusMsg != nil {
		in, out := &in.PeerStatusMsg, &out.PeerStatusMsg
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.PeerUptime = in.PeerUptime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCDomainStatus.
func (in *VPCDomainStatus) DeepCopy() *VPCDomainStatus {
	if in == nil {
		return nil
	}
	out := new(VPCDomainStatus)
	in.DeepCopyInto(out)
	return out
}
