apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - leaf1-lo0.yaml
  - leaf1-lo1.yaml
  - leaf2-lo0.yaml
  - leaf2-lo1.yaml
  - leaf3-lo0.yaml
  - leaf3-lo1.yaml
  - spine1-lo0.yaml
  - spine1-lo1.yaml
  - spine2-lo0.yaml
  - spine2-lo1.yaml
