// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

/*
Package openconfig is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

This package was generated by ygnmi version: v0.12.0: (ygot: v0.29.20)
using the following YANG input files:
  - ./yang/release/models/interfaces/openconfig-interfaces.yang
  - ./yang/release/models/interfaces/openconfig-if-ip.yang
  - ./yang/third_party/ietf/iana-if-type.yang

Imported modules were sourced from:
  - ./yang/doc
  - ./yang/regexp-tests
  - ./yang/release/models
  - ./yang/release/models/acl
  - ./yang/release/models/aft
  - ./yang/release/models/ate
  - ./yang/release/models/bfd
  - ./yang/release/models/bgp
  - ./yang/release/models/catalog
  - ./yang/release/models/defined-sets
  - ./yang/release/models/devices-manifest
  - ./yang/release/models/ethernet-segments
  - ./yang/release/models/extensions
  - ./yang/release/models/firewall
  - ./yang/release/models/flex-algo
  - ./yang/release/models/gnpsi
  - ./yang/release/models/gnsi
  - ./yang/release/models/gribi
  - ./yang/release/models/grpc
  - ./yang/release/models/interfaces
  - ./yang/release/models/isis
  - ./yang/release/models/keychain
  - ./yang/release/models/lacp
  - ./yang/release/models/lldp
  - ./yang/release/models/local-routing
  - ./yang/release/models/macsec
  - ./yang/release/models/mpls
  - ./yang/release/models/multicast
  - ./yang/release/models/network-instance
  - ./yang/release/models/oam
  - ./yang/release/models/openflow
  - ./yang/release/models/optical-transport
  - ./yang/release/models/ospf
  - ./yang/release/models/p4rt
  - ./yang/release/models/pcep
  - ./yang/release/models/platform
  - ./yang/release/models/policy
  - ./yang/release/models/policy-forwarding
  - ./yang/release/models/probes
  - ./yang/release/models/ptp
  - ./yang/release/models/qos
  - ./yang/release/models/relay-agent
  - ./yang/release/models/rib
  - ./yang/release/models/sampling
  - ./yang/release/models/segment-routing
  - ./yang/release/models/stp
  - ./yang/release/models/system
  - ./yang/release/models/telemetry
  - ./yang/release/models/types
  - ./yang/release/models/vlan
  - ./yang/release/models/wifi
  - ./yang/third_party/ietf
*/
package openconfig

import (
	"reflect"

	"github.com/openconfig/ygot/ygot"
)

// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_Address_Status": {
		1: {Name: "PREFERRED"},
		2: {Name: "DEPRECATED"},
		3: {Name: "INVALID"},
		4: {Name: "INACCESSIBLE"},
		5: {Name: "UNKNOWN"},
		6: {Name: "TENTATIVE"},
		7: {Name: "DUPLICATE"},
		8: {Name: "OPTIMISTIC"},
	},
	"E_Ethernet_DuplexMode": {
		1: {Name: "FULL"},
		2: {Name: "HALF"},
	},
	"E_Ethernet_NegotiatedDuplexMode": {
		1: {Name: "FULL"},
		2: {Name: "HALF"},
	},
	"E_IETFInterfaces_InterfaceType": {
		1:   {Name: "a12MppSwitch", DefiningModule: "iana-if-type"},
		2:   {Name: "aal2", DefiningModule: "iana-if-type"},
		3:   {Name: "aal5", DefiningModule: "iana-if-type"},
		4:   {Name: "actelisMetaLOOP", DefiningModule: "iana-if-type"},
		5:   {Name: "adsl", DefiningModule: "iana-if-type"},
		6:   {Name: "adsl2", DefiningModule: "iana-if-type"},
		7:   {Name: "adsl2plus", DefiningModule: "iana-if-type"},
		8:   {Name: "aflane8023", DefiningModule: "iana-if-type"},
		9:   {Name: "aflane8025", DefiningModule: "iana-if-type"},
		10:  {Name: "aluELP", DefiningModule: "iana-if-type"},
		11:  {Name: "aluEpon", DefiningModule: "iana-if-type"},
		12:  {Name: "aluEponLogicalLink", DefiningModule: "iana-if-type"},
		13:  {Name: "aluEponOnu", DefiningModule: "iana-if-type"},
		14:  {Name: "aluEponPhysicalUni", DefiningModule: "iana-if-type"},
		15:  {Name: "aluGponOnu", DefiningModule: "iana-if-type"},
		16:  {Name: "aluGponPhysicalUni", DefiningModule: "iana-if-type"},
		17:  {Name: "arap", DefiningModule: "iana-if-type"},
		18:  {Name: "arcnet", DefiningModule: "iana-if-type"},
		19:  {Name: "arcnetPlus", DefiningModule: "iana-if-type"},
		20:  {Name: "async", DefiningModule: "iana-if-type"},
		21:  {Name: "atm", DefiningModule: "iana-if-type"},
		22:  {Name: "atmDxi", DefiningModule: "iana-if-type"},
		23:  {Name: "atmFuni", DefiningModule: "iana-if-type"},
		24:  {Name: "atmIma", DefiningModule: "iana-if-type"},
		25:  {Name: "atmLogical", DefiningModule: "iana-if-type"},
		26:  {Name: "atmRadio", DefiningModule: "iana-if-type"},
		27:  {Name: "atmSubInterface", DefiningModule: "iana-if-type"},
		28:  {Name: "atmVciEndPt", DefiningModule: "iana-if-type"},
		29:  {Name: "atmVirtual", DefiningModule: "iana-if-type"},
		30:  {Name: "atmbond", DefiningModule: "iana-if-type"},
		31:  {Name: "aviciOpticalEther", DefiningModule: "iana-if-type"},
		32:  {Name: "basicISDN", DefiningModule: "iana-if-type"},
		33:  {Name: "bgppolicyaccounting", DefiningModule: "iana-if-type"},
		34:  {Name: "bits", DefiningModule: "iana-if-type"},
		35:  {Name: "bridge", DefiningModule: "iana-if-type"},
		36:  {Name: "bsc", DefiningModule: "iana-if-type"},
		37:  {Name: "cableDownstreamRfPort", DefiningModule: "iana-if-type"},
		38:  {Name: "capwapDot11Bss", DefiningModule: "iana-if-type"},
		39:  {Name: "capwapDot11Profile", DefiningModule: "iana-if-type"},
		40:  {Name: "capwapWtpVirtualRadio", DefiningModule: "iana-if-type"},
		41:  {Name: "cblVectaStar", DefiningModule: "iana-if-type"},
		42:  {Name: "cctEmul", DefiningModule: "iana-if-type"},
		43:  {Name: "ces", DefiningModule: "iana-if-type"},
		44:  {Name: "channel", DefiningModule: "iana-if-type"},
		45:  {Name: "ciscoISLvlan", DefiningModule: "iana-if-type"},
		46:  {Name: "cnr", DefiningModule: "iana-if-type"},
		47:  {Name: "coffee", DefiningModule: "iana-if-type"},
		48:  {Name: "compositeLink", DefiningModule: "iana-if-type"},
		49:  {Name: "dcn", DefiningModule: "iana-if-type"},
		50:  {Name: "ddnX25", DefiningModule: "iana-if-type"},
		51:  {Name: "digitalPowerline", DefiningModule: "iana-if-type"},
		52:  {Name: "digitalWrapperOverheadChannel", DefiningModule: "iana-if-type"},
		53:  {Name: "dlsw", DefiningModule: "iana-if-type"},
		54:  {Name: "docsCableDownstream", DefiningModule: "iana-if-type"},
		55:  {Name: "docsCableMCmtsDownstream", DefiningModule: "iana-if-type"},
		56:  {Name: "docsCableMaclayer", DefiningModule: "iana-if-type"},
		57:  {Name: "docsCableNdf", DefiningModule: "iana-if-type"},
		58:  {Name: "docsCableNdr", DefiningModule: "iana-if-type"},
		59:  {Name: "docsCableScte55d1FwdOob", DefiningModule: "iana-if-type"},
		60:  {Name: "docsCableScte55d1RetOob", DefiningModule: "iana-if-type"},
		61:  {Name: "docsCableScte55d2DsOob", DefiningModule: "iana-if-type"},
		62:  {Name: "docsCableScte55d2UsOob", DefiningModule: "iana-if-type"},
		63:  {Name: "docsCableUpstream", DefiningModule: "iana-if-type"},
		64:  {Name: "docsCableUpstreamChannel", DefiningModule: "iana-if-type"},
		65:  {Name: "docsCableUpstreamRfPort", DefiningModule: "iana-if-type"},
		66:  {Name: "docsOfdmDownstream", DefiningModule: "iana-if-type"},
		67:  {Name: "docsOfdmaUpstream", DefiningModule: "iana-if-type"},
		68:  {Name: "ds0", DefiningModule: "iana-if-type"},
		69:  {Name: "ds0Bundle", DefiningModule: "iana-if-type"},
		70:  {Name: "ds1", DefiningModule: "iana-if-type"},
		71:  {Name: "ds1FDL", DefiningModule: "iana-if-type"},
		72:  {Name: "ds3", DefiningModule: "iana-if-type"},
		73:  {Name: "dtm", DefiningModule: "iana-if-type"},
		74:  {Name: "dvbAsiIn", DefiningModule: "iana-if-type"},
		75:  {Name: "dvbAsiOut", DefiningModule: "iana-if-type"},
		76:  {Name: "dvbRccDownstream", DefiningModule: "iana-if-type"},
		77:  {Name: "dvbRccMacLayer", DefiningModule: "iana-if-type"},
		78:  {Name: "dvbRccUpstream", DefiningModule: "iana-if-type"},
		79:  {Name: "dvbRcsMacLayer", DefiningModule: "iana-if-type"},
		80:  {Name: "dvbRcsTdma", DefiningModule: "iana-if-type"},
		81:  {Name: "dvbTdm", DefiningModule: "iana-if-type"},
		82:  {Name: "e1", DefiningModule: "iana-if-type"},
		83:  {Name: "econet", DefiningModule: "iana-if-type"},
		84:  {Name: "eon", DefiningModule: "iana-if-type"},
		85:  {Name: "eplrs", DefiningModule: "iana-if-type"},
		86:  {Name: "escon", DefiningModule: "iana-if-type"},
		87:  {Name: "ethernet3Mbit", DefiningModule: "iana-if-type"},
		88:  {Name: "ethernetCsmacd", DefiningModule: "iana-if-type"},
		89:  {Name: "fast", DefiningModule: "iana-if-type"},
		90:  {Name: "fastEther", DefiningModule: "iana-if-type"},
		91:  {Name: "fastEtherFX", DefiningModule: "iana-if-type"},
		92:  {Name: "fastdsl", DefiningModule: "iana-if-type"},
		93:  {Name: "fcipLink", DefiningModule: "iana-if-type"},
		94:  {Name: "fddi", DefiningModule: "iana-if-type"},
		95:  {Name: "fibreChannel", DefiningModule: "iana-if-type"},
		96:  {Name: "frDlciEndPt", DefiningModule: "iana-if-type"},
		97:  {Name: "frForward", DefiningModule: "iana-if-type"},
		98:  {Name: "frameRelay", DefiningModule: "iana-if-type"},
		99:  {Name: "frameRelayInterconnect", DefiningModule: "iana-if-type"},
		100: {Name: "frameRelayMPI", DefiningModule: "iana-if-type"},
		101: {Name: "frameRelayService", DefiningModule: "iana-if-type"},
		102: {Name: "frf16MfrBundle", DefiningModule: "iana-if-type"},
		103: {Name: "g703at2mb", DefiningModule: "iana-if-type"},
		104: {Name: "g703at64k", DefiningModule: "iana-if-type"},
		105: {Name: "g9981", DefiningModule: "iana-if-type"},
		106: {Name: "g9982", DefiningModule: "iana-if-type"},
		107: {Name: "g9983", DefiningModule: "iana-if-type"},
		108: {Name: "gfast", DefiningModule: "iana-if-type"},
		109: {Name: "gfp", DefiningModule: "iana-if-type"},
		110: {Name: "gigabitEthernet", DefiningModule: "iana-if-type"},
		111: {Name: "gpon", DefiningModule: "iana-if-type"},
		112: {Name: "gr303IDT", DefiningModule: "iana-if-type"},
		113: {Name: "gr303RDT", DefiningModule: "iana-if-type"},
		114: {Name: "gtp", DefiningModule: "iana-if-type"},
		115: {Name: "h323Gatekeeper", DefiningModule: "iana-if-type"},
		116: {Name: "h323Proxy", DefiningModule: "iana-if-type"},
		117: {Name: "hdh1822", DefiningModule: "iana-if-type"},
		118: {Name: "hdlc", DefiningModule: "iana-if-type"},
		119: {Name: "hdsl2", DefiningModule: "iana-if-type"},
		120: {Name: "hiperlan2", DefiningModule: "iana-if-type"},
		121: {Name: "hippi", DefiningModule: "iana-if-type"},
		122: {Name: "hippiInterface", DefiningModule: "iana-if-type"},
		123: {Name: "homepna", DefiningModule: "iana-if-type"},
		124: {Name: "hostPad", DefiningModule: "iana-if-type"},
		125: {Name: "hssi", DefiningModule: "iana-if-type"},
		126: {Name: "hyperchannel", DefiningModule: "iana-if-type"},
		127: {Name: "iana-interface-type", DefiningModule: "iana-if-type"},
		128: {Name: "ibm370parChan", DefiningModule: "iana-if-type"},
		129: {Name: "idsl", DefiningModule: "iana-if-type"},
		130: {Name: "ieee1394", DefiningModule: "iana-if-type"},
		131: {Name: "ieee80211", DefiningModule: "iana-if-type"},
		132: {Name: "ieee80212", DefiningModule: "iana-if-type"},
		133: {Name: "ieee802154", DefiningModule: "iana-if-type"},
		134: {Name: "ieee80216WMAN", DefiningModule: "iana-if-type"},
		135: {Name: "ieee8023adLag", DefiningModule: "iana-if-type"},
		136: {Name: "if-gsn", DefiningModule: "iana-if-type"},
		137: {Name: "ifPwType", DefiningModule: "iana-if-type"},
		138: {Name: "ifVfiType", DefiningModule: "iana-if-type"},
		139: {Name: "ilan", DefiningModule: "iana-if-type"},
		140: {Name: "imt", DefiningModule: "iana-if-type"},
		141: {Name: "infiniband", DefiningModule: "iana-if-type"},
		142: {Name: "interleave", DefiningModule: "iana-if-type"},
		143: {Name: "ip", DefiningModule: "iana-if-type"},
		144: {Name: "ipForward", DefiningModule: "iana-if-type"},
		145: {Name: "ipOverAtm", DefiningModule: "iana-if-type"},
		146: {Name: "ipOverCdlc", DefiningModule: "iana-if-type"},
		147: {Name: "ipOverClaw", DefiningModule: "iana-if-type"},
		148: {Name: "ipSwitch", DefiningModule: "iana-if-type"},
		149: {Name: "isdn", DefiningModule: "iana-if-type"},
		150: {Name: "isdns", DefiningModule: "iana-if-type"},
		151: {Name: "isdnu", DefiningModule: "iana-if-type"},
		152: {Name: "iso88022llc", DefiningModule: "iana-if-type"},
		153: {Name: "iso88023Csmacd", DefiningModule: "iana-if-type"},
		154: {Name: "iso88024TokenBus", DefiningModule: "iana-if-type"},
		155: {Name: "iso88025CRFPInt", DefiningModule: "iana-if-type"},
		156: {Name: "iso88025Dtr", DefiningModule: "iana-if-type"},
		157: {Name: "iso88025Fiber", DefiningModule: "iana-if-type"},
		158: {Name: "iso88025TokenRing", DefiningModule: "iana-if-type"},
		159: {Name: "iso88026Man", DefiningModule: "iana-if-type"},
		160: {Name: "isup", DefiningModule: "iana-if-type"},
		161: {Name: "l2vlan", DefiningModule: "iana-if-type"},
		162: {Name: "l3ipvlan", DefiningModule: "iana-if-type"},
		163: {Name: "l3ipxvlan", DefiningModule: "iana-if-type"},
		164: {Name: "lapb", DefiningModule: "iana-if-type"},
		165: {Name: "lapd", DefiningModule: "iana-if-type"},
		166: {Name: "lapf", DefiningModule: "iana-if-type"},
		167: {Name: "linegroup", DefiningModule: "iana-if-type"},
		168: {Name: "lmp", DefiningModule: "iana-if-type"},
		169: {Name: "localTalk", DefiningModule: "iana-if-type"},
		170: {Name: "macSecControlledIF", DefiningModule: "iana-if-type"},
		171: {Name: "macSecUncontrolledIF", DefiningModule: "iana-if-type"},
		172: {Name: "mediaMailOverIp", DefiningModule: "iana-if-type"},
		173: {Name: "mfSigLink", DefiningModule: "iana-if-type"},
		174: {Name: "miox25", DefiningModule: "iana-if-type"},
		175: {Name: "mocaVersion1", DefiningModule: "iana-if-type"},
		176: {Name: "modem", DefiningModule: "iana-if-type"},
		177: {Name: "mpc", DefiningModule: "iana-if-type"},
		178: {Name: "mpegTransport", DefiningModule: "iana-if-type"},
		179: {Name: "mpls", DefiningModule: "iana-if-type"},
		180: {Name: "mplsTunnel", DefiningModule: "iana-if-type"},
		181: {Name: "msdsl", DefiningModule: "iana-if-type"},
		182: {Name: "mvl", DefiningModule: "iana-if-type"},
		183: {Name: "myrinet", DefiningModule: "iana-if-type"},
		184: {Name: "nfas", DefiningModule: "iana-if-type"},
		185: {Name: "nsip", DefiningModule: "iana-if-type"},
		186: {Name: "opticalChannel", DefiningModule: "iana-if-type"},
		187: {Name: "opticalChannelGroup", DefiningModule: "iana-if-type"},
		188: {Name: "opticalTransport", DefiningModule: "iana-if-type"},
		189: {Name: "other", DefiningModule: "iana-if-type"},
		190: {Name: "otnOdu", DefiningModule: "iana-if-type"},
		191: {Name: "otnOtu", DefiningModule: "iana-if-type"},
		192: {Name: "para", DefiningModule: "iana-if-type"},
		193: {Name: "pdnEtherLoop1", DefiningModule: "iana-if-type"},
		194: {Name: "pdnEtherLoop2", DefiningModule: "iana-if-type"},
		195: {Name: "pip", DefiningModule: "iana-if-type"},
		196: {Name: "plc", DefiningModule: "iana-if-type"},
		197: {Name: "pon155", DefiningModule: "iana-if-type"},
		198: {Name: "pon622", DefiningModule: "iana-if-type"},
		199: {Name: "pos", DefiningModule: "iana-if-type"},
		200: {Name: "ppp", DefiningModule: "iana-if-type"},
		201: {Name: "pppMultilinkBundle", DefiningModule: "iana-if-type"},
		202: {Name: "primaryISDN", DefiningModule: "iana-if-type"},
		203: {Name: "propAtm", DefiningModule: "iana-if-type"},
		204: {Name: "propBWAp2Mp", DefiningModule: "iana-if-type"},
		205: {Name: "propCnls", DefiningModule: "iana-if-type"},
		206: {Name: "propDocsWirelessDownstream", DefiningModule: "iana-if-type"},
		207: {Name: "propDocsWirelessMaclayer", DefiningModule: "iana-if-type"},
		208: {Name: "propDocsWirelessUpstream", DefiningModule: "iana-if-type"},
		209: {Name: "propMultiplexor", DefiningModule: "iana-if-type"},
		210: {Name: "propPointToPointSerial", DefiningModule: "iana-if-type"},
		211: {Name: "propVirtual", DefiningModule: "iana-if-type"},
		212: {Name: "propWirelessP2P", DefiningModule: "iana-if-type"},
		213: {Name: "proteon10Mbit", DefiningModule: "iana-if-type"},
		214: {Name: "proteon80Mbit", DefiningModule: "iana-if-type"},
		215: {Name: "ptm", DefiningModule: "iana-if-type"},
		216: {Name: "q2931", DefiningModule: "iana-if-type"},
		217: {Name: "qam", DefiningModule: "iana-if-type"},
		218: {Name: "qllc", DefiningModule: "iana-if-type"},
		219: {Name: "radioMAC", DefiningModule: "iana-if-type"},
		220: {Name: "radsl", DefiningModule: "iana-if-type"},
		221: {Name: "reachDSL", DefiningModule: "iana-if-type"},
		222: {Name: "regular1822", DefiningModule: "iana-if-type"},
		223: {Name: "rfc1483", DefiningModule: "iana-if-type"},
		224: {Name: "rfc877x25", DefiningModule: "iana-if-type"},
		225: {Name: "rpr", DefiningModule: "iana-if-type"},
		226: {Name: "rs232", DefiningModule: "iana-if-type"},
		227: {Name: "rsrb", DefiningModule: "iana-if-type"},
		228: {Name: "sdci", DefiningModule: "iana-if-type"},
		229: {Name: "sdlc", DefiningModule: "iana-if-type"},
		230: {Name: "sdsl", DefiningModule: "iana-if-type"},
		231: {Name: "shdsl", DefiningModule: "iana-if-type"},
		232: {Name: "sip", DefiningModule: "iana-if-type"},
		233: {Name: "sipSig", DefiningModule: "iana-if-type"},
		234: {Name: "sipTg", DefiningModule: "iana-if-type"},
		235: {Name: "sixToFour", DefiningModule: "iana-if-type"},
		236: {Name: "slip", DefiningModule: "iana-if-type"},
		237: {Name: "smdsDxi", DefiningModule: "iana-if-type"},
		238: {Name: "smdsIcip", DefiningModule: "iana-if-type"},
		239: {Name: "softwareLoopback", DefiningModule: "iana-if-type"},
		240: {Name: "sonet", DefiningModule: "iana-if-type"},
		241: {Name: "sonetOverheadChannel", DefiningModule: "iana-if-type"},
		242: {Name: "sonetPath", DefiningModule: "iana-if-type"},
		243: {Name: "sonetVT", DefiningModule: "iana-if-type"},
		244: {Name: "srp", DefiningModule: "iana-if-type"},
		245: {Name: "ss7SigLink", DefiningModule: "iana-if-type"},
		246: {Name: "stackToStack", DefiningModule: "iana-if-type"},
		247: {Name: "starLan", DefiningModule: "iana-if-type"},
		248: {Name: "tdlc", DefiningModule: "iana-if-type"},
		249: {Name: "teLink", DefiningModule: "iana-if-type"},
		250: {Name: "termPad", DefiningModule: "iana-if-type"},
		251: {Name: "tr008", DefiningModule: "iana-if-type"},
		252: {Name: "transpHdlc", DefiningModule: "iana-if-type"},
		253: {Name: "tunnel", DefiningModule: "iana-if-type"},
		254: {Name: "ultra", DefiningModule: "iana-if-type"},
		255: {Name: "usb", DefiningModule: "iana-if-type"},
		256: {Name: "v11", DefiningModule: "iana-if-type"},
		257: {Name: "v35", DefiningModule: "iana-if-type"},
		258: {Name: "v36", DefiningModule: "iana-if-type"},
		259: {Name: "v37", DefiningModule: "iana-if-type"},
		260: {Name: "vdsl", DefiningModule: "iana-if-type"},
		261: {Name: "vdsl2", DefiningModule: "iana-if-type"},
		262: {Name: "virtualIpAddress", DefiningModule: "iana-if-type"},
		263: {Name: "virtualTg", DefiningModule: "iana-if-type"},
		264: {Name: "vmwareNicTeam", DefiningModule: "iana-if-type"},
		265: {Name: "vmwareVirtualNic", DefiningModule: "iana-if-type"},
		266: {Name: "voiceDID", DefiningModule: "iana-if-type"},
		267: {Name: "voiceEBS", DefiningModule: "iana-if-type"},
		268: {Name: "voiceEM", DefiningModule: "iana-if-type"},
		269: {Name: "voiceEMFGD", DefiningModule: "iana-if-type"},
		270: {Name: "voiceEncap", DefiningModule: "iana-if-type"},
		271: {Name: "voiceFGDEANA", DefiningModule: "iana-if-type"},
		272: {Name: "voiceFGDOS", DefiningModule: "iana-if-type"},
		273: {Name: "voiceFXO", DefiningModule: "iana-if-type"},
		274: {Name: "voiceFXS", DefiningModule: "iana-if-type"},
		275: {Name: "voiceOverAtm", DefiningModule: "iana-if-type"},
		276: {Name: "voiceOverCable", DefiningModule: "iana-if-type"},
		277: {Name: "voiceOverFrameRelay", DefiningModule: "iana-if-type"},
		278: {Name: "voiceOverIp", DefiningModule: "iana-if-type"},
		279: {Name: "wwanPP", DefiningModule: "iana-if-type"},
		280: {Name: "wwanPP2", DefiningModule: "iana-if-type"},
		281: {Name: "x213", DefiningModule: "iana-if-type"},
		282: {Name: "x25huntGroup", DefiningModule: "iana-if-type"},
		283: {Name: "x25mlp", DefiningModule: "iana-if-type"},
		284: {Name: "x25ple", DefiningModule: "iana-if-type"},
		285: {Name: "x86Laps", DefiningModule: "iana-if-type"},
		286: {Name: "xboxWireless", DefiningModule: "iana-if-type"},
	},
	"E_IfAggregate_AggregationType": {
		1: {Name: "LACP"},
		2: {Name: "STATIC"},
	},
	"E_IfEthernet_ETHERNET_SPEED": {
		1:  {Name: "SPEED_100GB", DefiningModule: "openconfig-if-ethernet"},
		2:  {Name: "SPEED_100MB", DefiningModule: "openconfig-if-ethernet"},
		3:  {Name: "SPEED_10GB", DefiningModule: "openconfig-if-ethernet"},
		4:  {Name: "SPEED_10MB", DefiningModule: "openconfig-if-ethernet"},
		5:  {Name: "SPEED_1GB", DefiningModule: "openconfig-if-ethernet"},
		6:  {Name: "SPEED_200GB", DefiningModule: "openconfig-if-ethernet"},
		7:  {Name: "SPEED_2500MB", DefiningModule: "openconfig-if-ethernet"},
		8:  {Name: "SPEED_25GB", DefiningModule: "openconfig-if-ethernet"},
		9:  {Name: "SPEED_400GB", DefiningModule: "openconfig-if-ethernet"},
		10: {Name: "SPEED_40GB", DefiningModule: "openconfig-if-ethernet"},
		11: {Name: "SPEED_50GB", DefiningModule: "openconfig-if-ethernet"},
		12: {Name: "SPEED_5GB", DefiningModule: "openconfig-if-ethernet"},
		13: {Name: "SPEED_600GB", DefiningModule: "openconfig-if-ethernet"},
		14: {Name: "SPEED_800GB", DefiningModule: "openconfig-if-ethernet"},
		15: {Name: "SPEED_UNKNOWN", DefiningModule: "openconfig-if-ethernet"},
	},
	"E_IfEthernet_INTERFACE_FEC": {
		1: {Name: "FEC_DISABLED", DefiningModule: "openconfig-if-ethernet"},
		2: {Name: "FEC_FC", DefiningModule: "openconfig-if-ethernet"},
		3: {Name: "FEC_RS528", DefiningModule: "openconfig-if-ethernet"},
		4: {Name: "FEC_RS544", DefiningModule: "openconfig-if-ethernet"},
		5: {Name: "FEC_RS544_2X_INTERLEAVE", DefiningModule: "openconfig-if-ethernet"},
	},
	"E_IfIp_IpAddressOrigin": {
		1: {Name: "OTHER"},
		2: {Name: "STATIC"},
		3: {Name: "DHCP"},
		4: {Name: "LINK_LAYER"},
		5: {Name: "RANDOM"},
	},
	"E_IfIp_Ipv4AddressType": {
		1: {Name: "PRIMARY"},
		2: {Name: "SECONDARY"},
	},
	"E_IfIp_NeighborOrigin": {
		1: {Name: "OTHER"},
		2: {Name: "STATIC"},
		3: {Name: "DYNAMIC"},
	},
	"E_InetTypes_Ipv6AddressType": {
		1: {Name: "GLOBAL_UNICAST"},
		2: {Name: "LINK_LOCAL_UNICAST"},
	},
	"E_Interface_AdminStatus": {
		1: {Name: "UP"},
		2: {Name: "DOWN"},
		3: {Name: "TESTING"},
	},
	"E_Interface_OperStatus": {
		2: {Name: "UP"},
		3: {Name: "DOWN"},
		4: {Name: "TESTING"},
		5: {Name: "UNKNOWN"},
		6: {Name: "DORMANT"},
		7: {Name: "NOT_PRESENT"},
		8: {Name: "LOWER_LAYER_DOWN"},
	},
	"E_Ipv6_LearnUnsolicited": {
		1: {Name: "NONE"},
		2: {Name: "GLOBAL"},
		3: {Name: "LINK_LOCAL"},
		4: {Name: "BOTH"},
	},
	"E_Neighbor_NeighborState": {
		1: {Name: "INCOMPLETE"},
		2: {Name: "REACHABLE"},
		3: {Name: "STALE"},
		4: {Name: "DELAY"},
		5: {Name: "PROBE"},
	},
	"E_ProxyArp_Mode": {
		1: {Name: "DISABLE"},
		2: {Name: "REMOTE_ONLY"},
		3: {Name: "ALL"},
	},
	"E_RouterAdvertisement_Mode": {
		1: {Name: "ALL"},
		2: {Name: "DISABLE_UNSOLICITED_RA"},
	},
	"E_TransportTypes_LoopbackModeType": {
		1: {Name: "NONE"},
		2: {Name: "FACILITY"},
		3: {Name: "TERMINAL"},
		4: {Name: "ASIC_PHY_LOCAL"},
		5: {Name: "ASIC_PHY_REMOTE"},
		6: {Name: "ASIC_MAC_LOCAL"},
		7: {Name: "ASIC_MAC_REMOTE"},
	},
	"E_VlanTypes_TPID_TYPES": {
		1: {Name: "TPID_0X8100", DefiningModule: "openconfig-vlan-types"},
		2: {Name: "TPID_0X88A8", DefiningModule: "openconfig-vlan-types"},
		3: {Name: "TPID_0X9100", DefiningModule: "openconfig-vlan-types"},
		4: {Name: "TPID_0X9200", DefiningModule: "openconfig-vlan-types"},
		5: {Name: "TPID_ANY", DefiningModule: "openconfig-vlan-types"},
	},
	"E_VlanTypes_VlanModeType": {
		1: {Name: "ACCESS"},
		2: {Name: "TRUNK"},
	},
	"E_VlanTypes_VlanStackAction": {
		1: {Name: "PUSH"},
		2: {Name: "POP"},
		3: {Name: "SWAP"},
	},
}

// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
func initΛEnumTypes() {
	ΛEnumTypes = map[string][]reflect.Type{
		"/interfaces/interface/aggregation/config/lag-type": []reflect.Type{
			reflect.TypeOf((E_IfAggregate_AggregationType)(0)),
		},
		"/interfaces/interface/aggregation/state/lag-type": []reflect.Type{
			reflect.TypeOf((E_IfAggregate_AggregationType)(0)),
		},
		"/interfaces/interface/aggregation/switched-vlan/config/interface-mode": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_VlanModeType)(0)),
		},
		"/interfaces/interface/aggregation/switched-vlan/state/interface-mode": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_VlanModeType)(0)),
		},
		"/interfaces/interface/config/loopback-mode": []reflect.Type{
			reflect.TypeOf((E_TransportTypes_LoopbackModeType)(0)),
		},
		"/interfaces/interface/config/tpid": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_TPID_TYPES)(0)),
		},
		"/interfaces/interface/config/type": []reflect.Type{
			reflect.TypeOf((E_IETFInterfaces_InterfaceType)(0)),
		},
		"/interfaces/interface/ethernet/config/duplex-mode": []reflect.Type{
			reflect.TypeOf((E_Ethernet_DuplexMode)(0)),
		},
		"/interfaces/interface/ethernet/config/fec-mode": []reflect.Type{
			reflect.TypeOf((E_IfEthernet_INTERFACE_FEC)(0)),
		},
		"/interfaces/interface/ethernet/config/port-speed": []reflect.Type{
			reflect.TypeOf((E_IfEthernet_ETHERNET_SPEED)(0)),
		},
		"/interfaces/interface/ethernet/state/duplex-mode": []reflect.Type{
			reflect.TypeOf((E_Ethernet_DuplexMode)(0)),
		},
		"/interfaces/interface/ethernet/state/fec-mode": []reflect.Type{
			reflect.TypeOf((E_IfEthernet_INTERFACE_FEC)(0)),
		},
		"/interfaces/interface/ethernet/state/negotiated-duplex-mode": []reflect.Type{
			reflect.TypeOf((E_Ethernet_NegotiatedDuplexMode)(0)),
		},
		"/interfaces/interface/ethernet/state/negotiated-port-speed": []reflect.Type{
			reflect.TypeOf((E_IfEthernet_ETHERNET_SPEED)(0)),
		},
		"/interfaces/interface/ethernet/state/port-speed": []reflect.Type{
			reflect.TypeOf((E_IfEthernet_ETHERNET_SPEED)(0)),
		},
		"/interfaces/interface/ethernet/switched-vlan/config/interface-mode": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_VlanModeType)(0)),
		},
		"/interfaces/interface/ethernet/switched-vlan/state/interface-mode": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_VlanModeType)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv4/addresses/address/config/type": []reflect.Type{
			reflect.TypeOf((E_IfIp_Ipv4AddressType)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv4/addresses/address/state/origin": []reflect.Type{
			reflect.TypeOf((E_IfIp_IpAddressOrigin)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv4/addresses/address/state/type": []reflect.Type{
			reflect.TypeOf((E_IfIp_Ipv4AddressType)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv4/neighbors/neighbor/state/origin": []reflect.Type{
			reflect.TypeOf((E_IfIp_NeighborOrigin)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv4/proxy-arp/config/mode": []reflect.Type{
			reflect.TypeOf((E_ProxyArp_Mode)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv4/proxy-arp/state/mode": []reflect.Type{
			reflect.TypeOf((E_ProxyArp_Mode)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/addresses/address/config/type": []reflect.Type{
			reflect.TypeOf((E_InetTypes_Ipv6AddressType)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/addresses/address/state/origin": []reflect.Type{
			reflect.TypeOf((E_IfIp_IpAddressOrigin)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/addresses/address/state/status": []reflect.Type{
			reflect.TypeOf((E_Address_Status)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/addresses/address/state/type": []reflect.Type{
			reflect.TypeOf((E_InetTypes_Ipv6AddressType)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/config/learn-unsolicited": []reflect.Type{
			reflect.TypeOf((E_Ipv6_LearnUnsolicited)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/neighbors/neighbor/state/neighbor-state": []reflect.Type{
			reflect.TypeOf((E_Neighbor_NeighborState)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/neighbors/neighbor/state/origin": []reflect.Type{
			reflect.TypeOf((E_IfIp_NeighborOrigin)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/router-advertisement/config/mode": []reflect.Type{
			reflect.TypeOf((E_RouterAdvertisement_Mode)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/router-advertisement/state/mode": []reflect.Type{
			reflect.TypeOf((E_RouterAdvertisement_Mode)(0)),
		},
		"/interfaces/interface/routed-vlan/ipv6/state/learn-unsolicited": []reflect.Type{
			reflect.TypeOf((E_Ipv6_LearnUnsolicited)(0)),
		},
		"/interfaces/interface/state/admin-status": []reflect.Type{
			reflect.TypeOf((E_Interface_AdminStatus)(0)),
		},
		"/interfaces/interface/state/loopback-mode": []reflect.Type{
			reflect.TypeOf((E_TransportTypes_LoopbackModeType)(0)),
		},
		"/interfaces/interface/state/oper-status": []reflect.Type{
			reflect.TypeOf((E_Interface_OperStatus)(0)),
		},
		"/interfaces/interface/state/tpid": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_TPID_TYPES)(0)),
		},
		"/interfaces/interface/state/type": []reflect.Type{
			reflect.TypeOf((E_IETFInterfaces_InterfaceType)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/config/type": []reflect.Type{
			reflect.TypeOf((E_IfIp_Ipv4AddressType)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/state/origin": []reflect.Type{
			reflect.TypeOf((E_IfIp_IpAddressOrigin)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/state/type": []reflect.Type{
			reflect.TypeOf((E_IfIp_Ipv4AddressType)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv4/neighbors/neighbor/state/origin": []reflect.Type{
			reflect.TypeOf((E_IfIp_NeighborOrigin)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv4/proxy-arp/config/mode": []reflect.Type{
			reflect.TypeOf((E_ProxyArp_Mode)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv4/proxy-arp/state/mode": []reflect.Type{
			reflect.TypeOf((E_ProxyArp_Mode)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/config/type": []reflect.Type{
			reflect.TypeOf((E_InetTypes_Ipv6AddressType)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/origin": []reflect.Type{
			reflect.TypeOf((E_IfIp_IpAddressOrigin)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/status": []reflect.Type{
			reflect.TypeOf((E_Address_Status)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/type": []reflect.Type{
			reflect.TypeOf((E_InetTypes_Ipv6AddressType)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/config/learn-unsolicited": []reflect.Type{
			reflect.TypeOf((E_Ipv6_LearnUnsolicited)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/neighbors/neighbor/state/neighbor-state": []reflect.Type{
			reflect.TypeOf((E_Neighbor_NeighborState)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/neighbors/neighbor/state/origin": []reflect.Type{
			reflect.TypeOf((E_IfIp_NeighborOrigin)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/router-advertisement/config/mode": []reflect.Type{
			reflect.TypeOf((E_RouterAdvertisement_Mode)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/router-advertisement/state/mode": []reflect.Type{
			reflect.TypeOf((E_RouterAdvertisement_Mode)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/ipv6/state/learn-unsolicited": []reflect.Type{
			reflect.TypeOf((E_Ipv6_LearnUnsolicited)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/state/admin-status": []reflect.Type{
			reflect.TypeOf((E_Interface_AdminStatus)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/state/oper-status": []reflect.Type{
			reflect.TypeOf((E_Interface_OperStatus)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/vlan/egress-mapping/config/tpid": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_TPID_TYPES)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/vlan/egress-mapping/config/vlan-stack-action": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_VlanStackAction)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/vlan/egress-mapping/state/tpid": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_TPID_TYPES)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/vlan/egress-mapping/state/vlan-stack-action": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_VlanStackAction)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/vlan/ingress-mapping/config/tpid": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_TPID_TYPES)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/vlan/ingress-mapping/config/vlan-stack-action": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_VlanStackAction)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/vlan/ingress-mapping/state/tpid": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_TPID_TYPES)(0)),
		},
		"/interfaces/interface/subinterfaces/subinterface/vlan/ingress-mapping/state/vlan-stack-action": []reflect.Type{
			reflect.TypeOf((E_VlanTypes_VlanStackAction)(0)),
		},
	}
}
