// Code generated by "stringer -type=AuthType"; DO NOT EDIT.

package snmp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MD5-0]
	_ = x[SHA-1]
	_ = x[SHA256-2]
	_ = x[SHA512-3]
}

const _AuthType_name = "MD5SHASHA256SHA512"

var _AuthType_index = [...]uint8{0, 3, 6, 12, 18}

func (i AuthType) String() string {
	if i >= AuthType(len(_AuthType_index)-1) {
		return "AuthType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthType_name[_AuthType_index[i]:_AuthType_index[i+1]]
}
