// Code generated by "stringer -type=Sec"; DO NOT EDIT.

package snmp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoAuth-0]
	_ = x[Auth-1]
	_ = x[Priv-2]
}

const _Sec_name = "NoAuthAuthPriv"

var _Sec_index = [...]uint8{0, 6, 10, 14}

func (i Sec) String() string {
	if i >= Sec(len(_Sec_index)-1) {
		return "Sec(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Sec_name[_Sec_index[i]:_Sec_index[i+1]]
}
