// Code generated by "stringer -type=Version"; DO NOT EDIT.

package snmp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[V1-0]
	_ = x[V2c-1]
	_ = x[V3-2]
}

const _Version_name = "V1V2cV3"

var _Version_index = [...]uint8{0, 2, 5, 7}

func (i Version) String() string {
	if i >= Version(len(_Version_index)-1) {
		return "Version(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Version_name[_Version_index[i]:_Version_index[i+1]]
}
