// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0

// This package enables the configuration of logging on a NXOS device. We must support the following configuration sample:
//   - logging level aaa 6
//   - logging history 6
//   - logging history size 500
//   - logging server 10.10.10.10 6 use-vrf management
//   - logging source-interface mgmt0
//   - logging origin-id hostname
//
// Which corresponds to the following YANG model:
//   - System/logging-items/loglevel-items/facility-items/Facility-list[facilityName=aaa]
//   - System/syslog-items/logginghistory-items
//   - System/syslog-items/logginghistory-items
//   - System/syslog-items/rdst-items/RemoteDest-list
//   - System/syslog-items/source-items
//   - System/syslog-items/originid-items
//
// Implementation notes:
//   - We must use the same severity for all facilities.
//   - Modifying just one facility severity level and calling Update() triggers a delete for all other entries in the facility list.
//     To avoid this behaviour the `toYGOT()` method MUST return a GoStruct with all facilities listed.
//   - Logging facilities are not enumerated in the YANG model and thus not generated by YGot.
//   - Wildcards are not supported on Cisco 9k gNMI and can't be used to set the severity level for all facilities.
//   - It is possible to configure all facilities at once via the CLI command `logging level all 7`.
//     -- The gNMI counterpart is `logging-items/loglevel-items": {"all": "enableall", "severity", "7"}`.
//   - enerates the following forbidden operation when using the "all" approach:
//     -- `internal processing error [error:operation-failed msg:logging level local7 : delete is not allowed]“
//     -- the function `appendFacilitiesDefaultSeverity()` implements this call and is left here for future reference
//   - We define a list of facilities for each NXOS version in facilities.go
//   - Syslog servers communicate only over TCP and UDP (no TLS).
package logging

import (
	"context"
	"fmt"
	"strings"

	"github.com/openconfig/ygot/ygot"

	nxos "github.com/ironcore-dev/network-operator/internal/provider/cisco/nxos/genyang"
	"github.com/ironcore-dev/network-operator/internal/provider/cisco/nxos/gnmiext"
)

//go:generate go run golang.org/x/tools/cmd/stringer@v0.35.0 -type=SeverityLevel
type SeverityLevel int

const (
	Emergency SeverityLevel = iota + 1
	Alert
	Critical
	Error
	Warning
	Notice
	Informational
	Debug
)

func SeverityLevelFrom(s string) SeverityLevel {
	switch strings.ToLower(s) {
	case "emergency":
		return Emergency
	case "alert":
		return Alert
	case "critical":
		return Critical
	case "error":
		return Error
	case "warning":
		return Warning
	case "notice":
		return Notice
	case "info", "informational":
		return Informational
	case "debug":
		return Debug
	default:
		return Informational
	}
}

//go:generate go run golang.org/x/tools/cmd/stringer@v0.35.0 -type=SyslogProto
type SyslogProto int

const (
	TCP SyslogProto = iota
	UDP
)

// Implements the DeviceConf interface.
var _ gnmiext.DeviceConf = (*Logging)(nil)

// SyslogServer represents the configuration for a single remote syslog server
type SyslogServer struct {
	// a hostname, IPv4, or IPv6 address
	Host string
	// port number of the syslog server
	Port uint32
	// transport protocol
	Proto SyslogProto
	// communicate over the specified VRF, if not specified the management VRF is used.
	Vrf string
	// severity level for the syslog server
	Level SeverityLevel
}

// History represents logger settings for local history
type History struct {
	Severity SeverityLevel
	Size     uint32
}

// Logging represents the entire logging configuration
type Logging struct {
	// Wether to enable the logging. Disabling will not necessarily delete the configuration on the switch.
	Enable bool
	// Origin-ID to use for all remote Syslog servers
	OriginID string
	// Interface used to reach the syslog servers
	SrcIf string
	// List of remote syslog servers
	Servers []*SyslogServer
	// History configuration
	History History
	// Default severity level for all facilities
	DefaultSeverity SeverityLevel
	// List of facilities to configure. If not defined, facilities will be set to the default severity level.
	Facilities []*Facility
}

type Facility struct {
	// The name of the facility.
	Name string
	// The log level for the facility.
	Severity SeverityLevel
}

func (l *Logging) ToYGOT(_ context.Context, _ gnmiext.Client) ([]gnmiext.Update, error) {
	if !l.Enable {
		return []gnmiext.Update{
			gnmiext.EditingUpdate{
				XPath: "System/syslog-items/source-items",
				Value: &nxos.Cisco_NX_OSDevice_System_SyslogItems_SourceItems{
					AdminState: nxos.Cisco_NX_OSDevice_Mon_AdminState_disabled,
				},
			},
		}, nil
	}

	defaultSeverity, err := toSeverityLevel(l.DefaultSeverity)
	if err != nil {
		return nil, err
	}

	// first configure all facilities to the default severity level
	lg := &nxos.Cisco_NX_OSDevice_System_LoggingItems{}
	lg.PopulateDefaults()
	li := lg.GetOrCreateLoglevelItems()
	li.PopulateDefaults()
	fi := li.GetOrCreateFacilityItems()
	// set all facilities
	for _, f := range AvailableFacilities {
		if _, ok := createOnlyFacilities[f]; ok {
			continue
		}
		if _, ok := invalidFacilities[f]; ok {
			continue
		}
		fl := fi.GetOrCreateFacilityList(f)
		fl.PopulateDefaults()
		fl.FacilityName = ygot.String(f)
		fl.SeverityLevel = defaultSeverity
	}

	// set user-defined levels
	for _, f := range l.Facilities {
		fl := fi.GetOrCreateFacilityList(f.Name)
		severity, err := toSeverityLevel(f.Severity)
		if err != nil {
			return nil, err
		}
		fl.SeverityLevel = severity
	}

	items := &nxos.Cisco_NX_OSDevice_System_SyslogItems_RdstItems{RemoteDestList: make(map[string]*nxos.Cisco_NX_OSDevice_System_SyslogItems_RdstItems_RemoteDestList, len(l.Servers))}
	for _, s := range l.Servers {
		var transport nxos.E_Cisco_NX_OSDevice_Mon_Transport
		switch s.Proto {
		case TCP:
			transport = nxos.Cisco_NX_OSDevice_Mon_Transport_tcp
		case UDP:
			transport = nxos.Cisco_NX_OSDevice_Mon_Transport_udp
		default:
			return nil, fmt.Errorf("logging: unsupported transport protocol in syslog definitions %v", s.Proto)
		}

		err := items.AppendRemoteDestList(&nxos.Cisco_NX_OSDevice_System_SyslogItems_RdstItems_RemoteDestList{
			Host:      ygot.String(s.Host),
			Severity:  nxos.E_Cisco_NX_OSDevice_Syslog_Severity(s.Level),
			VrfName:   ygot.String(s.Vrf),
			Port:      ygot.Uint32(s.Port),
			Transport: transport,
		})
		if err != nil {
			return nil, err
		}
	}

	return []gnmiext.Update{
		gnmiext.EditingUpdate{
			XPath: "System/syslog-items/source-items",
			Value: &nxos.Cisco_NX_OSDevice_System_SyslogItems_SourceItems{
				AdminState: nxos.Cisco_NX_OSDevice_Mon_AdminState_enabled,
				IfName:     ygot.String(l.SrcIf),
			},
		},
		gnmiext.EditingUpdate{
			XPath: "System/syslog-items/originid-items",
			Value: &nxos.Cisco_NX_OSDevice_System_SyslogItems_OriginidItems{
				Idvalue: ygot.String(l.OriginID),
			},
		},
		gnmiext.EditingUpdate{
			XPath: "System/syslog-items/logginghistory-items",
			Value: &nxos.Cisco_NX_OSDevice_System_SyslogItems_LogginghistoryItems{
				Level: nxos.E_Cisco_NX_OSDevice_Syslog_Severity(l.History.Severity),
				Size:  ygot.Uint32(l.History.Size),
			},
		},
		gnmiext.EditingUpdate{
			XPath: "System/logging-items",
			Value: lg,
		},
		gnmiext.ReplacingUpdate{
			XPath: "System/syslog-items/rdst-items",
			Value: items,
		},
	}, nil
}

func (v *Logging) Reset(_ context.Context, _ gnmiext.Client) ([]gnmiext.Update, error) {
	lg := &nxos.Cisco_NX_OSDevice_System_LoggingItems{}
	lg.PopulateDefaults()
	li := lg.GetOrCreateLoglevelItems()
	li.PopulateDefaults()
	fi := li.GetOrCreateFacilityItems()
	for _, f := range AvailableFacilities {
		fl := fi.GetOrCreateFacilityList(f)
		fl.PopulateDefaults()
		fl.FacilityName = ygot.String(f)
		fl.SeverityLevel = nxos.Cisco_NX_OSDevice_Syslog_Severity_UNSET
	}

	hi := &nxos.Cisco_NX_OSDevice_System_SyslogItems_LogginghistoryItems{}
	hi.PopulateDefaults()

	oidi := &nxos.Cisco_NX_OSDevice_System_SyslogItems_OriginidItems{}
	oidi.PopulateDefaults()
	oidi.Idtype = nxos.Cisco_NX_OSDevice_Syslog_OriginIdType_UNSET

	ri := &nxos.Cisco_NX_OSDevice_System_SyslogItems_RdstItems{}
	ri.PopulateDefaults()

	return []gnmiext.Update{
		gnmiext.EditingUpdate{
			XPath: "System/syslog-items/source-items",
			Value: &nxos.Cisco_NX_OSDevice_System_SyslogItems_SourceItems{
				AdminState: nxos.Cisco_NX_OSDevice_Mon_AdminState_disabled,
			},
		},
		gnmiext.EditingUpdate{
			XPath: "System/syslog-items/originid-items",
			Value: oidi,
		},
		gnmiext.EditingUpdate{
			XPath: "System/syslog-items/logginghistory-items",
			Value: hi,
		},
		gnmiext.EditingUpdate{
			XPath: "System/logging-items",
			Value: lg,
		},
		gnmiext.EditingUpdate{
			XPath: "System/syslog-items/rdst-items",
			Value: ri,
		},
	}, nil
}

func toSeverityLevel(level SeverityLevel) (nxos.E_Cisco_NX_OSDevice_Syslog_Severity, error) {
	switch level {
	case Emergency:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_emergencies, nil
	case Alert:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_alerts, nil
	case Critical:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_critical, nil
	case Error:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_errors, nil
	case Warning:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_warnings, nil
	case Notice:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_notifications, nil
	case Informational:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_information, nil
	case Debug:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_debugging, nil
	default:
		return nxos.Cisco_NX_OSDevice_Syslog_Severity_UNSET, fmt.Errorf("logging: unknown severity level %s", level)
	}
}
