// Code generated by "stringer -type=SeverityLevel"; DO NOT EDIT.

package logging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Emergency-1]
	_ = x[Alert-2]
	_ = x[Critical-3]
	_ = x[Error-4]
	_ = x[Warning-5]
	_ = x[Notice-6]
	_ = x[Informational-7]
	_ = x[Debug-8]
}

const _SeverityLevel_name = "EmergencyAlertCriticalErrorWarningNoticeInformationalDebug"

var _SeverityLevel_index = [...]uint8{0, 9, 14, 22, 27, 34, 40, 53, 58}

func (i SeverityLevel) String() string {
	i -= 1
	if i < 0 || i >= SeverityLevel(len(_SeverityLevel_index)-1) {
		return "SeverityLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SeverityLevel_name[_SeverityLevel_index[i]:_SeverityLevel_index[i+1]]
}
