// Code generated by "stringer -type=SyslogProto"; DO NOT EDIT.

package logging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TCP-0]
	_ = x[UDP-1]
}

const _SyslogProto_name = "TCPUDP"

var _SyslogProto_index = [...]uint8{0, 3, 6}

func (i SyslogProto) String() string {
	if i < 0 || i >= SyslogProto(len(_SyslogProto_index)-1) {
		return "SyslogProto(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SyslogProto_name[_SyslogProto_index[i]:_SyslogProto_index[i+1]]
}
