# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
# SPDX-License-Identifier: Apache-2.0

name: Lint

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  lint:
    name: Check Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
  vulnerabilities:
    name: Check Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck -format text ./...
  spelling:
    name: Check Spelling Errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run typos
        uses: crate-ci/typos@v1
        env:
          CLICOLOR: "1"
  shellcheck:
    name: Check Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run shellcheck
        uses: reviewdog/action-shellcheck@v1
  license:
    name: Check Licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Dependency Licenses Review
        run: make check-dependency-licenses
      - name: Check if source code files have license header
        run: make check-addlicense
