# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
# SPDX-License-Identifier: Apache-2.0

name: Test E2E

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  test-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          version: v0.31.0
          kubectl_version: v1.35.0
          cluster_name: network
      - name: Running E2E Tests
        run: |
          go mod download
          make test-e2e
